In [1]:
import numpy as np
import time

In [2]:
t1 = time.time()
a = []
for x in range(1000):
    a.append(x**2)
t2 = time.time()
print(t2-t1)

0.01708221435546875


In [3]:
t3 = time.time()
b = np.arange(1000)**2 # 所有都平方
t4 = time.time()
print(t4-t3)

0.0010085105895996094


# 数组介绍

In [5]:
c = np.array([4,5.5,'6'])#不能出现多个数据类型 
c

array(['4', '5.5', '6'], dtype='<U32')

In [6]:
# 创建数组的几种方式
# 1、 使用np.array
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
# 2.使用np.arange
b = np.arange(0,10,2)
b

array([0, 2, 4, 6, 8])

In [11]:
# 3.np.random
c = np.random.random()
c

0.6517566022675803

In [12]:
c = np.random.random((2,2)) #2行2列0到1的随机数
c

array([[0.33458853, 0.39899295],
       [0.772875  , 0.79294068]])

In [13]:
# 4. np.random.randint
c = np.random.randint(0,9,size=(4,4))#int型随机数
c

array([[1, 2, 1, 2],
       [5, 8, 5, 5],
       [2, 8, 2, 5],
       [6, 6, 2, 5]])

In [15]:
# 5. 特殊函数
a1 = np.zeros((2,2))
a2 = np.ones((3,3))
a3 = np.eye(4)
a2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])