In [1]:
import numpy as np

In [2]:
# 1. 一维数组的索引和切片
a1 = np.arange(10)
print(a1[4])
print(a1[4:6])
print(a1[::2])#使用步长
print(a1[-1])#最后一个值

4
[4 5]
[0 2 4 6 8]
9


In [3]:
# 2. 多维数组
a2 = np.random.randint(0,10,size=(4,6))
a2

array([[2, 2, 3, 1, 2, 8],
       [8, 9, 4, 8, 9, 6],
       [4, 9, 6, 5, 1, 1],
       [4, 0, 8, 0, 7, 4]])

In [4]:
a2[0]

array([2, 2, 3, 1, 2, 8])

In [5]:
a2[1:3]# 3比2多一位

array([[8, 9, 4, 8, 9, 6],
       [4, 9, 6, 5, 1, 1]])

In [6]:
a2[[0,2,3]]#获取不连续的行

array([[2, 2, 3, 1, 2, 8],
       [4, 9, 6, 5, 1, 1],
       [4, 0, 8, 0, 7, 4]])

In [7]:
a2[1,1]

9

In [8]:
a2[[1,2],[4,5]] #(1,4)和(2,5)

array([9, 1])

In [9]:
a2[1:3,4:6]

array([[9, 6],
       [1, 1]])

In [11]:
a2[:,[1,3]]#获取1，3列

array([[2, 1],
       [9, 8],
       [9, 5],
       [0, 0]])

In [13]:
# 布尔索引
a3 = np.arange(24).reshape((4,6))
a3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [14]:
a2 < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [17]:
a2[(a2<5) | (a2>10)]

array([2, 2, 3, 1, 2, 4, 4, 1, 1, 4, 0, 0, 4])

In [18]:
#数组值的替换
a4 =  np.random.randint(0,10,size=(3,5))
a4

array([[8, 3, 8, 2, 5],
       [6, 2, 2, 9, 9],
       [7, 9, 0, 9, 7]])

In [20]:
a4[1]= np.array([1,2,3,4,5])
a4

array([[8, 3, 8, 2, 5],
       [1, 2, 3, 4, 5],
       [7, 9, 0, 9, 7]])

In [25]:
a4[a4<3] = 1
a4

array([[8, 3, 8, 1, 5],
       [1, 1, 3, 4, 5],
       [7, 9, 1, 9, 7]])

In [28]:
result = np.where( a3<5, 0, 1) #如果满足条件就替换为0，不满足就替换为1
result

array([[0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])