In [1]:
import numpy as np

In [2]:
a1 = np.random.randint(0,5,size=(3,5))

In [3]:
a1

array([[1, 3, 3, 2, 4],
       [0, 0, 2, 0, 3],
       [4, 1, 1, 2, 0]])

In [4]:
a1*2#所有元素×2


array([[2, 6, 6, 4, 8],
       [0, 0, 4, 0, 6],
       [8, 2, 2, 4, 0]])

In [5]:
a2 = np.random.randint(0,5,size=(3,5))
a2

array([[2, 0, 3, 2, 4],
       [3, 3, 0, 1, 2],
       [1, 3, 3, 4, 2]])

In [6]:
a1+a2

array([[3, 3, 6, 4, 8],
       [3, 3, 2, 1, 5],
       [5, 4, 4, 6, 2]])

In [7]:
a4 = np.random.randint(0,5,size=(3,1))
a4

array([[0],
       [1],
       [0]])

In [8]:
a1+a4#数组的广播机制 a4和a1的每一列相加

array([[1, 3, 3, 2, 4],
       [1, 1, 3, 1, 4],
       [4, 1, 1, 2, 0]])

In [9]:
#广播原则：从末尾开始算的维度相同或者其中有一个为1的话是可以进行运算的
a6 = np.random.randint(0,5,size=(3,8,2))
a7 = np.random.randint(0,5,size=(8,2))
print(a6)
print('='*30)
print(a7)
print("="*30)
print(a6+a7)

[[[1 1]
  [0 0]
  [2 4]
  [4 4]
  [4 4]
  [1 3]
  [2 0]
  [4 3]]

 [[4 4]
  [2 4]
  [0 0]
  [2 1]
  [4 3]
  [1 1]
  [2 0]
  [0 1]]

 [[3 1]
  [3 4]
  [0 0]
  [2 3]
  [4 1]
  [3 4]
  [2 3]
  [1 0]]]
[[4 4]
 [4 2]
 [0 1]
 [1 0]
 [0 3]
 [2 4]
 [3 1]
 [0 0]]
[[[5 5]
  [4 2]
  [2 5]
  [5 4]
  [4 7]
  [3 7]
  [5 1]
  [4 3]]

 [[8 8]
  [6 6]
  [0 1]
  [3 1]
  [4 6]
  [3 5]
  [5 1]
  [0 1]]

 [[7 5]
  [7 6]
  [0 1]
  [3 3]
  [4 4]
  [5 8]
  [5 4]
  [1 0]]]
