In [1]:
import numpy as np

In [2]:
a1 = np.random.randint(0,10,size=(3,4))
a1

array([[8, 1, 2, 9],
       [7, 1, 2, 1],
       [0, 9, 1, 2]])

In [3]:
a1.reshape((2,6))#reshape不改变原数组
a1

array([[8, 1, 2, 9],
       [7, 1, 2, 1],
       [0, 9, 1, 2]])

In [4]:
a1.resize((4,3))#resize改变了原数组
a1

array([[8, 1, 2],
       [9, 7, 1],
       [2, 1, 0],
       [9, 1, 2]])

In [5]:
#flatten返回拷贝  ravel返回引用 - 结果就是对ravel返回的值修改会影响原数组 而flatten不会
a2 = np.random.randint(0,10,size=(3,4))
a2

array([[3, 0, 7, 6],
       [9, 9, 4, 9],
       [3, 4, 2, 8]])

In [10]:
a3 = a2.flatten()
a3[0]=100
print(a2)

[[3 0 7 6]
 [9 9 4 9]
 [3 4 2 8]]


In [11]:
a4 = a2.ravel()
a4[0]=100
print(a2)

[[100   0   7   6]
 [  9   9   4   9]
 [  3   4   2   8]]


In [8]:
a2

array([[3, 0, 7, 6],
       [9, 9, 4, 9],
       [3, 4, 2, 8]])

In [13]:
#数组叠加vstack hstack concatenate
vstack1 = np.random.randint(0,10,size=(3,4))
vstack1

array([[1, 1, 0, 4],
       [4, 7, 6, 9],
       [2, 0, 1, 5]])

In [14]:
vstack2 = np.random.randint(0,10,size=(2,4))
vstack2

array([[0, 9, 0, 0],
       [7, 2, 2, 2]])

In [20]:
vstack3 = np.vstack([vstack1,vstack2])
print(vstack3)
vstack4 = np.concatenate([vstack1,vstack2],axis=0)
print(vstack4)

[[1 1 0 4]
 [4 7 6 9]
 [2 0 1 5]
 [0 9 0 0]
 [7 2 2 2]]
[[1 1 0 4]
 [4 7 6 9]
 [2 0 1 5]
 [0 9 0 0]
 [7 2 2 2]]


In [16]:
h1 = np.random.randint(0,10,size=(3,4))
h1

array([[1, 4, 3, 0],
       [9, 8, 8, 3],
       [7, 7, 4, 2]])

In [17]:
h2 = np.random.randint(0,10,size=(3,1))
h2

array([[9],
       [9],
       [0]])

In [18]:
h3 = np.hstack([h1,h2])
h3

array([[1, 4, 3, 0, 9],
       [9, 8, 8, 3, 9],
       [7, 7, 4, 2, 0]])

In [21]:
h4 = np.concatenate([vstack1,vstack2],axis=None)
h4

array([1, 1, 0, 4, 4, 7, 6, 9, 2, 0, 1, 5, 0, 9, 0, 0, 7, 2, 2, 2])

In [22]:
#数组切割 hsplit
hs1 = np.random.randint(0,10,size=(3,4))
print(hs1)

[[0 6 2 6]
 [2 1 9 6]
 [2 0 4 2]]


In [23]:
np.hsplit(hs1,2)#分成两列

[array([[0, 6],
        [2, 1],
        [2, 0]]),
 array([[2, 6],
        [9, 6],
        [4, 2]])]

In [24]:
np.hsplit(hs1,(1,2))#在对应编号列的前面切割

[array([[0],
        [2],
        [2]]),
 array([[6],
        [1],
        [0]]),
 array([[2, 6],
        [9, 6],
        [4, 2]])]

In [27]:
vs1 = np.random.randint(0,10,size=(4,5))
vs1

array([[7, 6, 8, 8, 0],
       [5, 7, 7, 7, 2],
       [9, 2, 6, 7, 6],
       [4, 1, 1, 8, 4]])

In [28]:
np.vsplit(vs1,4)

[array([[7, 6, 8, 8, 0]]),
 array([[5, 7, 7, 7, 2]]),
 array([[9, 2, 6, 7, 6]]),
 array([[4, 1, 1, 8, 4]])]

In [29]:
np.vsplit(vs1,(1,3))

[array([[7, 6, 8, 8, 0]]),
 array([[5, 7, 7, 7, 2],
        [9, 2, 6, 7, 6]]),
 array([[4, 1, 1, 8, 4]])]

In [30]:
#np.split(vs1,4,axis=0)

In [31]:
#数组转置
t1 = np.random.randint(0,10,size=(3,4))
t1 

array([[0, 3, 1, 8],
       [0, 0, 8, 5],
       [8, 5, 8, 6]])

In [32]:
t1.T
#t1.transpose()返回的是引用

array([[0, 0, 8],
       [3, 0, 5],
       [1, 8, 8],
       [8, 5, 6]])

In [33]:
#矩阵相乘
t1.dot(t1.T)

array([[ 74,  48,  71],
       [ 48,  89,  94],
       [ 71,  94, 189]])