In [1]:
import numpy as np

In [2]:
#不拷贝:单纯的赋值
a = np.arange(12)
b = a
print(b is a)

True


In [4]:
#浅拷贝：返回了引用
c = a.view()
print(c is a)
c[0] = 100
a

False


array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [5]:
#深拷贝：
d = a.copy()
print(d is a)
d[1]=200
a

False


array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [6]:
d

array([100, 200,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])