In [1]:
import numpy as np

In [2]:
scores = np.random.randint(0,100,size=(20,2))
scores

array([[14, 51],
       [62, 53],
       [98,  8],
       [60, 24],
       [81, 60],
       [76, 97],
       [60, 62],
       [62, 39],
       [ 2, 60],
       [36, 84],
       [13, 85],
       [60,  9],
       [ 0, 82],
       [92, 51],
       [58, 27],
       [39,  5],
       [41, 12],
       [17, 38],
       [54, 99],
       [28, 12]])

In [6]:
np.savetxt("scors.csv",scores,delimiter=",",header="english,math",comments = "",fmt="%d")

In [8]:
np.loadtxt("scors.csv",dtype=int,delimiter=",",skiprows=1)

array([[14, 51],
       [62, 53],
       [98,  8],
       [60, 24],
       [81, 60],
       [76, 97],
       [60, 62],
       [62, 39],
       [ 2, 60],
       [36, 84],
       [13, 85],
       [60,  9],
       [ 0, 82],
       [92, 51],
       [58, 27],
       [39,  5],
       [41, 12],
       [17, 38],
       [54, 99],
       [28, 12]])

In [9]:
#np独有的存储方案: 特殊数据格式，且可以存储多维数组
c = np.random.randint(0,10,size=(10,2))
np.save("c",c)#np.savez会压缩数据

In [10]:
c1 = np.load("c.npy")
c1

array([[0, 8],
       [5, 0],
       [3, 0],
       [5, 9],
       [1, 2],
       [5, 8],
       [3, 8],
       [7, 5],
       [2, 0],
       [9, 2]])