In [1]:
import numpy as np

In [3]:
data = np.random.randint(0,10,size=(3,5))
data

array([[6, 7, 2, 4, 6],
       [9, 7, 4, 1, 0],
       [1, 3, 4, 4, 1]])

In [9]:
#NAN属于浮点类型
data = data.astype(float)
data[0,1]=np.NAN
data

array([[ 6., nan,  2.,  4.,  6.],
       [ 9.,  7.,  4.,  1.,  0.],
       [ 1.,  3.,  4.,  4.,  1.]])

In [10]:
np.NAN == np.NAN

False

In [11]:
data/0

<ipython-input-11-93938293822a>:1: RuntimeWarning: divide by zero encountered in true_divide
  data/0
<ipython-input-11-93938293822a>:1: RuntimeWarning: invalid value encountered in true_divide
  data/0


array([[inf, nan, inf, inf, inf],
       [inf, inf, inf, inf, nan],
       [inf, inf, inf, inf, inf]])

In [12]:
#NAN删除
data[1,2]=np.NAN
data

array([[ 6., nan,  2.,  4.,  6.],
       [ 9.,  7., nan,  1.,  0.],
       [ 1.,  3.,  4.,  4.,  1.]])

In [16]:
data[~np.isnan(data)]

array([6., 2., 4., 6., 9., 7., 1., 0., 1., 3., 4., 4., 1.])

In [19]:
#删除nan所在的行
lines = np.where(np.isnan(data))[0]
data = np.delete(data,lines,axis=0)
data

array([[1., 3., 4., 4., 1.]])

In [37]:
#NAN替换
scores = np.loadtxt("nan_scores.csv",delimiter=",",skiprows=1,encoding = "utf-8", dtype = str)
scores[scores ==""] = np.NAN #将str型数据转化为float型的nan
scores1 = scores.astype(float)
scores1

array([[23. , 67. ],
       [34. , 45.5],
       [45. ,  nan],
       [ nan, 23. ],
       [56. , 12. ]])

In [38]:
scores1[np.isnan(scores1)] = 0
scores1.sum(axis=1)#按行求和 除了delete以外，其他大部分函数axis=1都是表示行

array([90. , 79.5, 45. , 23. , 68. ])

In [44]:
scores2 = scores.astype(float).copy()
for x in range(scores2.shape[1]):#加range使其可迭代
    col = scores2[:,x]
    non_nan_col = col[~np.isnan(col)]
    mean = non_nan_col.mean()
    col[np.isnan(col)] = mean
scores2

array([[23.   , 67.   ],
       [34.   , 45.5  ],
       [45.   , 36.875],
       [39.5  , 23.   ],
       [56.   , 12.   ]])