In [1]:
import numpy as np

In [6]:
#np.random.seed(1)
np.random.rand(2,3)#(0,1)的随机数

array([[0.34556073, 0.39676747, 0.53881673],
       [0.41919451, 0.6852195 , 0.20445225]])

In [7]:
np.random.randn(2,3)#标准正态分布

array([[-0.85990661,  1.77260763, -1.11036305],
       [ 0.18121427,  0.56434487, -0.56651023]])

In [10]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#np.random.choice(10,size=(3,4))
np.random.choice(data,size=(3,4))

array([[9, 1, 0, 1],
       [8, 8, 3, 9],
       [8, 7, 3, 6]])

In [13]:
data1 = np.arange(10)
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.random.shuffle(data1)#打乱顺序
data1

array([8, 5, 1, 3, 9, 2, 7, 4, 6, 0])