In [1]:
import numpy as np

In [2]:
a = np.arange(0,4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [3]:
#axis=0代表0维，第一层括号 axis=1代表第二层括号
#如果指定某个轴操作会使用轴下对应的元素的第一个第二个等等这样操作
a.sum(axis=0)

array([2, 4])

In [4]:
a.max(axis=0)

array([2, 3])