In [2]:
import numpy as np
a = np.random.uniform(-10,10,size=(3,5))
a

array([[-8.75153147,  4.97962655, -3.35588057, -8.77109898, -9.8108674 ],
       [ 1.31871577,  0.02644098,  2.96662965,  5.36894203,  4.90214104],
       [-8.29252699,  6.72310596,  0.61641392, -6.35517315, -9.94844923]])

In [3]:
np.abs(a)

array([[8.75153147, 4.97962655, 3.35588057, 8.77109898, 9.8108674 ],
       [1.31871577, 0.02644098, 2.96662965, 5.36894203, 4.90214104],
       [8.29252699, 6.72310596, 0.61641392, 6.35517315, 9.94844923]])

In [5]:
np.ceil(a)#朝着无穷大的方向取整

array([[-8.,  5., -3., -8., -9.],
       [ 2.,  1.,  3.,  6.,  5.],
       [-8.,  7.,  1., -6., -9.]])

In [8]:
np.floor_divide(7,2)# 相当于/

3

#在Python内置函数和np函数同时存在的时候优先使用np函数

In [10]:
#布尔函数和排序函数
a.any()

True

In [11]:
(a>0).all()

False

In [12]:
np.sort(a)#按行 不加axis默认从最里面的轴排序

array([[-9.8108674 , -8.77109898, -8.75153147, -3.35588057,  4.97962655],
       [ 0.02644098,  1.31871577,  2.96662965,  4.90214104,  5.36894203],
       [-9.94844923, -8.29252699, -6.35517315,  0.61641392,  6.72310596]])

In [13]:
np.sort(a,axis=0)#按列

array([[-8.75153147,  0.02644098, -3.35588057, -8.77109898, -9.94844923],
       [-8.29252699,  4.97962655,  0.61641392, -6.35517315, -9.8108674 ],
       [ 1.31871577,  6.72310596,  2.96662965,  5.36894203,  4.90214104]])

In [15]:
b = np.random.randint(0,10,size=(3,5))
b

array([[7, 2, 2, 9, 4],
       [0, 9, 4, 7, 1],
       [4, 1, 7, 2, 8]])

In [16]:
b.sort()
b

array([[2, 2, 4, 7, 9],
       [0, 1, 4, 7, 9],
       [1, 2, 4, 7, 8]])

In [17]:
np.argsort(b)# argument of sorted array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [18]:
-np.sort(-b)#按降序排序1

array([[9, 7, 4, 2, 2],
       [9, 7, 4, 1, 0],
       [8, 7, 4, 2, 1]])

In [19]:
index = np.argsort(-a)#降序排序2
np.take(a,index)

array([[ 4.97962655, -3.35588057, -8.75153147, -8.77109898, -9.8108674 ],
       [-8.77109898, -9.8108674 , -3.35588057, -8.75153147,  4.97962655],
       [ 4.97962655, -3.35588057, -8.77109898, -8.75153147, -9.8108674 ]])

#其他函数

In [20]:
c = np.random.randint(0,100,size=(3,20))
c

array([[80, 32, 33, 46, 72, 68, 49, 95, 91, 73, 34, 69, 55, 11, 82, 20,
        81, 80, 38, 98],
       [32, 68, 80, 46, 97, 19, 58, 78, 84, 15, 98, 31, 22,  4, 79, 69,
        46, 33, 91, 44],
       [86, 42, 93, 35, 83, 24,  1, 63, 36, 47,  3, 36, 50, 55, 24, 29,
         8, 72, 61, 30]])

In [23]:
#按照我们想要的方式执行函数
#axis=1 按照行
def get_mean(x):
    y = x[np.logical_and(x!=x.max(),x!=x.min())].mean()
    return y
np.apply_along_axis(get_mean,axis=1,arr=c)

array([61.        , 55.11111111, 43.55555556])

In [28]:
np.linspace(0,1,10)#平均分为几份

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
d = np.random.randint(0,10,size=(3,5))
np.unique(d)#出现的数字

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [30]:
np.unique(d,return_counts=True)#出现的数字+出现的次数

(array([0, 1, 2, 3, 4, 5, 6, 7, 9]),
 array([1, 1, 2, 3, 2, 2, 1, 2, 1], dtype=int64))